# .github/workflows/sync-repo.yml
name: Sync Repository

on:
  workflow_call:
    inputs:
      target_repo: 
        description: "The repository to sync"
        required: true
        type: string
      foundation_repo:
        description: "The core foundation repository"
        required: true
        type: string



env:
    GIT_PAT: ${{ secrets.GEN_PAT }}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout foundation repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.foundation_repo }}
          ref: main
          fetch-depth: 0

      - name: Set up Git authentication and clone target repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git clone https://x-access-token:$GIT_PAT@github.com/svensson1982/core-web.git

      - name: Merge foundation tokens into target main
        run: |
          cd ${{ inputs.target_repo }}
          git checkout main
          git pull origin main
          git remote add foundation https://x-access-token:$GIT_PAT@github.com/${{ inputs.foundation_repo }}
          git fetch foundation
          git checkout -b temp-merge
          git checkout foundation/main -- tokens
          git add tokens
          git commit -m "Merged tokens directory from foundation into ${{ inputs.target_repo }}"
          git checkout main
          git merge temp-merge
          git push origin main
          git branch -d temp-merge






# name: Sync Repos

# on:
#   push:
#     branches:
#       - main
#     paths: 
#       - 'tokens/**'
#       - '!.github/workflows/**' 

# env:
#     GIT_PAT: ${{ secrets.GIT_PAT }}

# jobs:
#   sync-repo:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         repo: [core-web.git, core-android.git, core-ios.git]

#     steps:
#       - name: Checkout core-foundation repository
#         uses: actions/checkout@v4
#         with:
#           repository: svensson1982/core-foundation
#           ref: main
#           fetch-depth: 0  # Get the full history

#       - name: Set up Git authentication for target repository
#         run: |
#           git config --global user.name "GitHub Action"
#           git config --global user.email "action@github.com"
#           git clone https://x-access-token:$GIT_PAT@github.com/svensson1982/core-web.git ${{ matrix.repo }}

#       # Step 3: Merge changes from core-foundation/main into target repository main
#       - name: Merge core-foundation tokens into target main
#         run: |
#           cd ${{ matrix.repo }}

#           # Fetch changes from target main
#           git checkout main
#           git pull origin main

#           # Add core-foundation as a remote and fetch its changes
#           git remote add foundation https://x-access-token:$GIT_PAT@github.com/svensson1982/core-foundation.git
#           git fetch foundation

#           # Create a temporary branch to perform the merge
#           git checkout -b temp-merge

#           # Merge only the tokens directory from core-foundation/main
#           git checkout foundation/main -- tokens

#           # Stage the changes
#           git add tokens

#           # Commit the changes
#           git commit -m "Merged tokens directory from core-foundation into core-web"

#           # Checkout main branch and merge the temporary branch
#           git checkout main
#           git merge temp-merge

#           # Push the merged changes back to target main
#           git push origin main

#           # Clean up the temporary branch
#           git branch -d temp-merge

#       - name: Remove if sync-repos.yml exists
#         run: |
#           cd core-web
#           if [ -f .github/workflows/sync-repos.yml ]; then
#             git rm --cached .github/workflows/sync-repos.yml
#             git commit -m "Remove sync-repos.yml from tracked files" || echo "No changes to commit"
#           fi
        
